### ISSUE TITLE
Diagramme erstellen

### ISSUE THREAD

**Issue by FX-139** [IBAIT18/group5#15]
Ablaufdiagramm des gesamten Quellcode wird von Paul gepusht. 
Klassendiagramme wurde erstellt und als Image geuploadet. 
technisches Diagramm ist vorhanden.

**Comment by patimue** [comment]
[Das Klassendiagramm im ersten Entwurf](https://github.com/IBAIT18/group5/blob/master/DC94685F-FEB0-49DF-9D1E-36094CA287D1.jpeg)

**Comment by FX-139** [comment]
[Konzeptgrafik 2 - nach dem MidReview erstellt](https://github.com/IBAIT18/group5/blob/master/Konzeptgrafik%202.JPG)

**Comment by patimue** [comment]
[Das Ablaufdiagramm für unser Programm](https://github.com/IBAIT18/group5/blob/master/IMG_0159.png)
)

**Comment by FX-139** [comment]
Aktuelle Diagramme sind hochgeladen und die, die in Frage kommen werden in der PRäsentation genutzt
