### ISSUE TITLE
Screenshots aus Programm für Präsentation

### ISSUE THREAD

**Issue by FX-139** [IBAIT18/group5#17]
einfach kurz ein paar nette Screenshots für die Präsentation wären prima :)

**Comment by Jokki14** [comment]
![Anfangsfenster](https://user-images.githubusercontent.com/48713089/58250857-9c0ee680-7d62-11e9-9395-fdaca99c8c46.PNG)
![Fächerauswahl](https://user-images.githubusercontent.com/48713089/58250858-9c0ee680-7d62-11e9-91bc-f8faf81fecdd.PNG)
![MaskeBewerber](https://user-images.githubusercontent.com/48713089/58250859-9c0ee680-7d62-11e9-97be-5a4ff7848abd.PNG)
![Ranking](https://user-images.githubusercontent.com/48713089/58250860-9c0ee680-7d62-11e9-9174-ef6d132bcd2c.PNG)
![ScoreRechner](https://user-images.githubusercontent.com/48713089/58250861-9ca77d00-7d62-11e9-8dac-fcddb3b52a35.PNG)

**Comment by FX-139** [comment]
Danke :)
