### ISSUE TITLE
GUI Grundlage schreiben

### ISSUE THREAD

**Issue by FX-139** [IBAIT18/group5#2]

**Comment by sischneider** [comment]
![Erwartete Unterlagen](https://user-images.githubusercontent.com/48749421/57517806-f007dd00-7317-11e9-8d95-8bfbfc70f492.PNG)
Hier sind nützliche Informationen, diese wir im Interface implementieren sollten.
Quelle:
https://de.statista.com/infografik/5092/bewerbungen-in-deutschland/
