### ISSUE TITLE
Präsentation erstellen

### ISSUE THREAD

**Issue by FX-139** [IBAIT18/group5#9]
Bitte am Beurteilungsbogen orientieren.

**Comment by patimue** [comment]
Schreibe jetzt am Code weiter, poste das bearbeitet später noch mit Kommentaren

**Comment by sischneider** [comment]
Werde die Präsentation des Projektes übernehmen

**Comment by FX-139** [comment]
Habe die [Zwischenversion](https://github.com/IBAIT18/group5/commit/5ac931c6b43812d17eee2ba52d2f973796a8dcf5) der PPTX hochgeladen

**Comment by FX-139** [comment]
Habe noch die eine Statistik Folie vergessen zu übertragen von Simon

**Comment by FX-139** [comment]
Ich habe die Änderungen aus dem heutigen Meeting notiert.
Die fertige Präsentation lade ich im Laufe des Nachmittags noch einmal hoch.

Bitte bei euren Folien noch das Feedback an mich, damit ich Details anpassen kann.

**Comment by FX-139** [comment]
Die [Präsentation in finaler Version] (https://github.com/IBAIT18/group5/blob/master/Version_final.pptx) ist hochgeladen. Tom Cruise Style hier in letzter Minute.
